name: Go

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.20'

            - name: Build to exe
              run: go build -o yamst.exe

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  prerelease: false
                  automatic_release_tag: 'latest'
                  files: |
                      *.exe
